### ISSUE TITLE
when can we get gem for v2?

### ISSUE THREAD

**Issue by anton-ivan** [billr578/shipwire#3]
I've used current version to connect to shipwire and even configuration doesn't work.

NoMethodError (undefined method `config' for Shipwire:Module):

I've got this error.

**Comment by billr578** [comment]
Hey @anton-ivan -

I haven't been actively developing this gem in a while since I don't work with Shipwire anymore.  I can look into why you're getting that error this week though - my guess is I documented something improperly.  There was a developer working on an updated gem to work with the Shipwire v3 API as a form of this gem at one point.

**Comment by anton-ivan** [comment]
I've managed to use V3 api now. thanks.
